### ISSUE TITLE
jnml validation fails

### ISSUE THREAD

**Issue by theiera** [OpenSourceBrain/GranularLayerSolinasNieusDAngelo2010#1]
The file generated by GenerateGranCellLayer.py fails validation by:

$ jnml -validate LEMS_Sim_Solinas2010.xml
 jNeuroML v0.7.3
Validating: /Users/theiera/git_blacksmith/GranularLayerSolinasNieusDAngelo2010/NeuroML2/LEMS_Sim_Solinas2010.xml
File: /Users/theiera/git_blacksmith/GranularLayerSolinasNieusDAngelo2010/NeuroML2/LEMS_Sim_Solinas2010.xml is not valid against the schema: /Schemas/NeuroML2/NeuroML_v2beta4.xsd!!
cvc-elt.1: Cannot find the declaration of element 'Lems'.

Validated 1 files: 0 passed, 1 failed

**Comment by pgleeson** [comment]
jnml -validate is not intended for validating LEMS*.xml files (i.e. LEMS files including a `<Simulation>` element, with root element `<Lems>`), just pure NeuroML2 files (containing root  `<neuroml>`, usually *.nml)
